### ISSUE TITLE
Cannot use test.only in tape

### ISSUE THREAD

**Issue by vvo** [revolunet/node-babel-boilerplate#1]
Test script should concatenate before passing to babel-node so that we can use test.only.

Other each file is ran one by one and .only does not work.

**Comment by revolunet** [comment]
thanks for suggestion, tell me if its better now :)

**Comment by vvo** [comment]
should be yes, I am not using the boilerplate, only found it on google while searching for "babel-node tape", thx!

So the solution is to use "babel-tape-runner" for googlers
